import { ApiInterface } from './interfaces/api';
export * from './models/data-model';
export * from './models/crud-model';
export * from './interfaces/crud-features';
export * from './models/decorators';
export * from './interfaces/attachable';
export * from './interfaces/workfloable';
export * from './apis/rest/api';
export * from './apis/graphql/api';
export * from './utils/types';
export declare let activeApi: ApiInterface;
export declare function setApi(api: ApiInterface): void;
export declare function getApi(): ApiInterface;
